"""
concordance_data.py
===================
Data store for the BNS/IPC Concordance mappings.
"""

from typing import List, Dict, Any

CONCORDANCE_DB: List[Dict[str, Any]] = [
    {
        "id": "cheating_fraud",
        "category": "Fraud & Cyber / Property",
        "offense_en": "Cheating and dishonestly inducing delivery of property (Financial / Online Fraud)",
        "offense_hi": "धोखाधड़ी और संपत्ति की बेईमानी से सुपुर्दगी (ऑनलाइन / वित्तीय फ्रॉड)",
        "bns_section": "318(4)",
        "bns_title": "Cheating and dishonestly inducing delivery of property",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "420",
        "ipc_title": "Cheating and dishonestly inducing delivery of property",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Cognizable",
        "bailable": "Non-Bailable",
        "compoundable": "Compoundable with permission of court",
        "punishment": "Imprisonment up to 7 years and fine",
        "triable_by": "Magistrate of the First Class",
        "bnss_procedure": "Section 35(3) BNSS notice applies if punishment <= 7 yrs (Police cannot arrest casually without recorded reasons).",
        "victim_guidance": "1. Immediately call 1930 or report on cybercrime.gov.in within 24 hrs to freeze beneficiary account. 2. Preserve bank UTR, transaction SMS, and WhatsApp chats. 3. File FIR under Sec 318(4) BNS + Sec 66D IT Act.",
        "accused_guidance": "1. Check if police served Section 35(3) BNSS notice (formerly 41A CrPC). 2. Cooperate with inquiry. 3. If arrest is threatened, apply for Anticipatory Bail under Section 482 BNSS (formerly 438 CrPC)."
    },
    {
        "id": "simple_cheating",
        "category": "Fraud & Deceit",
        "offense_en": "Cheating (General Deception)",
        "offense_hi": "सामान्य धोखाधड़ी (छल)",
        "bns_section": "318(2)",
        "bns_title": "Punishment for cheating",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "417",
        "ipc_title": "Punishment for cheating",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Non-Cognizable",
        "bailable": "Bailable",
        "compoundable": "Compoundable with permission of person cheated",
        "punishment": "Imprisonment up to 3 years, or fine, or both",
        "triable_by": "Any Magistrate",
        "bnss_procedure": "Non-cognizable; police cannot register FIR directly without Magistrate order under Sec 174 BNSS.",
        "victim_guidance": "File a private criminal complaint before Magistrate under Section 223 BNSS.",
        "accused_guidance": "Offense is bailable as a matter of right. Police cannot arrest without warrant."
    },
    {
        "id": "criminal_breach_of_trust",
        "category": "Financial & Business",
        "offense_en": "Criminal Breach of Trust (Misappropriation of Money/Property)",
        "offense_hi": "आपराधिक विश्वासघात (रुपयों या संपत्ति का गबन)",
        "bns_section": "316(2)",
        "bns_title": "Criminal breach of trust",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "406",
        "ipc_title": "Punishment for criminal breach of trust",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Cognizable",
        "bailable": "Non-Bailable",
        "compoundable": "Compoundable with court permission",
        "punishment": "Imprisonment up to 5 years, or fine, or both",
        "triable_by": "Magistrate of the First Class",
        "bnss_procedure": "Sec 35(3) BNSS applies. Police must record written justification before any arrest.",
        "victim_guidance": "Collect written agreements, receipts, account statements proving entrustment of funds.",
        "accused_guidance": "Highlight that commercial/business dispute is purely civil in nature, not criminal."
    },
    {
        "id": "theft",
        "category": "Property Crimes",
        "offense_en": "Theft (Chori)",
        "offense_hi": "चोरी",
        "bns_section": "303(2)",
        "bns_title": "Theft in general",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "379",
        "ipc_title": "Punishment for theft",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Cognizable",
        "bailable": "Non-Bailable (Bailable if first-time minor community service under BNS)",
        "compoundable": "Compoundable with owner's consent",
        "punishment": "Imprisonment up to 3 years, or fine, or community service",
        "triable_by": "Any Magistrate",
        "bnss_procedure": "BNS introduces 'Community Service' for first-time petty theft under 5,000 INR upon return of property.",
        "victim_guidance": "File e-FIR or visit nearest police station immediately. Get FIR copy free of cost.",
        "accused_guidance": "For petty theft under Rs 5,000, apply for community service relief under BNS 303(2) proviso."
    },
    {
        "id": "extortion",
        "category": "Intimidation & Blackmail",
        "offense_en": "Extortion / Blackmail / Demanding Money under Threat",
        "offense_hi": "जबरन वसूली / ब्लैकमेल / धमकी देकर पैसे ऐंठना",
        "bns_section": "308(2)",
        "bns_title": "Extortion",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "384",
        "ipc_title": "Punishment for extortion",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Cognizable",
        "bailable": "Non-Bailable",
        "compoundable": "Non-Compoundable",
        "punishment": "Imprisonment up to 3 years, or fine, or both (Up to 7-10 yrs if threat of death/grievous hurt)",
        "triable_by": "Magistrate of the First Class",
        "bnss_procedure": "Cognizable offense. Police must register FIR under Sec 173 BNSS.",
        "victim_guidance": "Preserve call recordings, screenshots, payment demands. Do not delete chats. File immediate police FIR.",
        "accused_guidance": "Seek legal representation; examine whether allegations are fabricated out of a business or personal rivalry."
    },
    {
        "id": "criminal_intimidation",
        "category": "Threats & Violence",
        "offense_en": "Criminal Intimidation (Jaan se maarne ki dhamki)",
        "offense_hi": "आपराधिक धमकी (जान से मारने या नुकसान पहुंचाने की धमकी)",
        "bns_section": "351(2) & 351(3)",
        "bns_title": "Criminal intimidation",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "506",
        "ipc_title": "Punishment for criminal intimidation",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Non-Cognizable (Simple) / Cognizable (Threat of death/grievous hurt)",
        "bailable": "Bailable",
        "compoundable": "Compoundable",
        "punishment": "Up to 2 years for simple intimidation; up to 7 years if threat to cause death or grievous hurt",
        "triable_by": "Any Magistrate (Simple) / Magistrate First Class (Death threat)",
        "bnss_procedure": "If death threat is alleged, police can lodge cognizable FIR under BNS 351(3).",
        "victim_guidance": "Record phone calls or take witnesses along. Submit written complaint to SHO or Superintendent of Police.",
        "accused_guidance": "Offense under 351(2) is bailable. Section 35(3) BNSS notice required before any coercive step."
    },
    {
        "id": "voluntarily_causing_hurt",
        "category": "Bodily Harm",
        "offense_en": "Voluntarily Causing Hurt / Assault (Maarpeet)",
        "offense_hi": "स्वेच्छा से चोट पहुंचाना / मारपीट",
        "bns_section": "115(2)",
        "bns_title": "Voluntarily causing hurt",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "323",
        "ipc_title": "Punishment for voluntarily causing hurt",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Non-Cognizable",
        "bailable": "Bailable",
        "compoundable": "Compoundable",
        "punishment": "Imprisonment up to 1 year, or fine up to Rs 10,000, or both",
        "triable_by": "Any Magistrate",
        "bnss_procedure": "If weapons or fractures are involved, it converts to Grievous Hurt (BNS 117 / IPC 325/326), which is Cognizable.",
        "victim_guidance": "Get immediate Medico-Legal Examination (MLC) at a Government Hospital. MLC is the vital evidence.",
        "accused_guidance": "Bailable offense. Get cross-complaint filed if you were also assaulted (mutual fight)."
    },
    {
        "id": "grievous_hurt",
        "category": "Bodily Harm",
        "offense_en": "Grievous Hurt / Severe Injury (Gambhir Chot / Fracture)",
        "offense_hi": "गंभीर चोट पहुंचाना (हड्डी टूटना, दांत टूटना, आंख/कान में चोट)",
        "bns_section": "117(2)",
        "bns_title": "Voluntarily causing grievous hurt",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "325",
        "ipc_title": "Punishment for voluntarily causing grievous hurt",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Cognizable",
        "bailable": "Bailable (Non-Bailable if dangerous weapon used under BNS 118)",
        "compoundable": "Compoundable with court permission",
        "punishment": "Imprisonment up to 7 years and fine",
        "triable_by": "Any Magistrate",
        "bnss_procedure": "Cognizable; FIR mandatory. Medical report (X-Ray/CT Scan) is conclusive proof.",
        "victim_guidance": "Preserve all hospital discharge summaries, X-Ray films, and MLC reports for police chargesheet.",
        "accused_guidance": "Section 35(3) BNSS notice applies. Engage counsel to secure regular or anticipatory bail."
    },
    {
        "id": "rash_driving",
        "category": "Road Traffic & Accidents",
        "offense_en": "Rash or Negligent Driving on Public Way",
        "offense_hi": "सड़क पर लापरवाही या तेजी से गाड़ी चलाना",
        "bns_section": "281",
        "bns_title": "Rash driving or riding on a public way",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "279",
        "ipc_title": "Rash driving or riding on a public way",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Cognizable",
        "bailable": "Bailable",
        "compoundable": "Non-Compoundable",
        "punishment": "Imprisonment up to 6 months, or fine up to Rs 1,000, or both",
        "triable_by": "Any Magistrate",
        "bnss_procedure": "Bailable at the police station upon furnishing personal bond and surety.",
        "victim_guidance": "Note down vehicle number, capture photos of collision, inform 112, obtain vehicle insurance details.",
        "accused_guidance": "Bailable at police station itself. Inform your vehicle insurance company within 48 hours."
    },
    {
        "id": "hit_and_run_death",
        "category": "Road Traffic & Accidents",
        "offense_en": "Causing Death by Negligence & Hit-and-Run",
        "offense_hi": "लापरवाही से मौत और दुर्घटना स्थल से भाग जाना (हिट एंड रन)",
        "bns_section": "106(1) & 106(2)",
        "bns_title": "Causing death by negligence & failure to report",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "304A",
        "ipc_title": "Causing death by negligence",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Cognizable",
        "bailable": "Bailable under 106(1) / Non-Bailable under 106(2) [Hit & Run without reporting]",
        "compoundable": "Non-Compoundable",
        "punishment": "106(1): Up to 5 yrs. 106(2): Up to 10 yrs if driver escapes without reporting to police/magistrate.",
        "triable_by": "Magistrate of the First Class",
        "bnss_procedure": "Crucial update: Under BNS 106(2), escaping without reporting carries severe 10-year term.",
        "victim_guidance": "File immediate FIR, request CCTV seizure from traffic cameras, claim compensation under MACT & Solatium Scheme.",
        "accused_guidance": "Never flee without reporting. Report the accident immediately to nearest police officer or magistrate to avoid 106(2)."
    },
    {
        "id": "matrimonial_cruelty",
        "category": "Family & Matrimonial",
        "offense_en": "Husband or Relative of Husband Subjecting Woman to Cruelty (Dowry/Harassment)",
        "offense_hi": "पति या उसके रिश्तेदारों द्वारा महिला के साथ क्रूरता (दहेज / प्रताड़ना)",
        "bns_section": "85 & 86",
        "bns_title": "Husband or relative of husband subjecting woman to cruelty",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "498A",
        "ipc_title": "Husband or relative of husband subjecting woman to cruelty",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Cognizable",
        "bailable": "Non-Bailable",
        "compoundable": "Non-Compoundable (States like AP/Delhi allow compounding)",
        "punishment": "Imprisonment up to 3 years and fine",
        "triable_by": "Magistrate of the First Class",
        "bnss_procedure": "Mandatory Arnesh Kumar / Sec 35 BNSS compliance: Police CANNOT arrest automatically. CAW cell mediation is mandatory first.",
        "victim_guidance": "File complaint before CAW (Crime Against Women) Cell / Women Police Station or under DV Act 2005 Sec 12.",
        "accused_guidance": "1. No automatic arrest (Sec 35 BNSS & Arnesh Kumar ruling). 2. Attend mediation. 3. File Anticipatory Bail under Sec 482 BNSS."
    },
    {
        "id": "dowry_death",
        "category": "Family & Matrimonial",
        "offense_en": "Dowry Death (Unnatural death within 7 years of marriage)",
        "offense_hi": "दहेज मृत्यु (विवाह के 7 वर्ष के भीतर असामान्य मृत्यु)",
        "bns_section": "80",
        "bns_title": "Dowry death",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "304B",
        "ipc_title": "Dowry death",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Cognizable",
        "bailable": "Non-Bailable",
        "compoundable": "Non-Compoundable",
        "punishment": "Rigorous imprisonment not less than 7 years, up to life imprisonment",
        "triable_by": "Court of Session",
        "bnss_procedure": "Executive Magistrate inquest mandatory under Sec 196 BNSS (formerly 176 CrPC).",
        "victim_guidance": "Ensure SDM Inquest is recorded without delay. Preserve all dowry demand communications.",
        "accused_guidance": "High presumption against accused under Sec 80 BNS and BSA. Immediate high-level criminal defense needed."
    },
    {
        "id": "defamation",
        "category": "Reputation & Speech",
        "offense_en": "Defamation (Maanhani / Online slander)",
        "offense_hi": "मानहानि (प्रतिष्ठा को नुकसान पहुंचाना / सोशल मीडिया पर बदनामी)",
        "bns_section": "356",
        "bns_title": "Defamation & Community Service provision",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "499 & 500",
        "ipc_title": "Defamation & Punishment for defamation",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Non-Cognizable",
        "bailable": "Bailable",
        "compoundable": "Compoundable",
        "punishment": "Simple imprisonment up to 2 years, or fine, or both, or Community Service (New in BNS)",
        "triable_by": "Court of Session (if against public servant) / Magistrate First Class",
        "bnss_procedure": "Police cannot file FIR directly. Requires a private criminal complaint under Sec 223 BNSS.",
        "victim_guidance": "Send a formal Legal Cease-and-Desist Notice through an advocate giving 15 days to retract and apologize.",
        "accused_guidance": "Bailable offense. Check statutory exceptions: Truth for public good, fair comment on public conduct."
    },
    {
        "id": "forgery",
        "category": "Fraud & Documents",
        "offense_en": "Forgery and Making False Documents (Fake papers / signatures)",
        "offense_hi": "जालसाजी (फर्जी दस्तावेज, जाली दस्तखत या कागजात बनाना)",
        "bns_section": "336 & 338",
        "bns_title": "Forgery and Forgery for purpose of cheating",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023",
        "ipc_section": "465 & 468",
        "ipc_title": "Punishment for forgery & Forgery for purpose of cheating",
        "ipc_act": "Indian Penal Code, 1860",
        "nature": "Non-Cognizable (Simple 336) / Cognizable (Forgery for cheating 338)",
        "bailable": "Bailable (336) / Non-Bailable (338)",
        "compoundable": "Non-Compoundable",
        "punishment": "336: Up to 2 yrs. 338: Up to 7 yrs and fine.",
        "triable_by": "Magistrate of the First Class",
        "bnss_procedure": "Forensic Handwriting / Forensic Science Laboratory (FSL) verification required.",
        "victim_guidance": "Collect original comparative signatures and registered land/bank records to prove forgery.",
        "accused_guidance": "Section 35(3) BNSS notice applies. Get documents verified through independent handwriting expert."
    },
    {
        "id": "cheque_bounce",
        "category": "Commercial & Banking",
        "offense_en": "Cheque Bounce for Insufficiency of Funds",
        "offense_hi": "चेक बाउंस (खाते में पर्याप्त धनराशि न होने के कारण)",
        "bns_section": "Section 138 NI Act (Special Act prevails)",
        "bns_title": "Dishonour of cheque for insufficiency, etc., of funds in the account",
        "bns_act": "Negotiable Instruments Act, 1881",
        "ipc_section": "Section 138 NI Act (with BNS 318 / IPC 420 if fraud present)",
        "ipc_title": "Dishonour of cheque under NI Act",
        "ipc_act": "Negotiable Instruments Act, 1881",
        "nature": "Non-Cognizable (Direct Complaint to Court)",
        "bailable": "Bailable",
        "compoundable": "Compoundable",
        "punishment": "Imprisonment up to 2 years, or fine up to double the cheque amount, or both",
        "triable_by": "Judicial Magistrate of the First Class / Metropolitan Magistrate",
        "bnss_procedure": "Summary trial procedure under Section 143 NI Act and BNSS.",
        "victim_guidance": "CRITICAL 30-DAY LIMITATION: 1. Send Statutory Demand Notice within 30 days of receiving bank return memo. 2. Give 15 days to pay. 3. If unpaid, file court complaint within next 30 days.",
        "accused_guidance": "Check if statutory notice was received within 30 days. Defend on lack of legally enforceable debt (e.g. security cheque misuse)."
    },
    {
        "id": "cyber_fraud_identity",
        "category": "Cyber Crime & Technology",
        "offense_en": "Cyber Identity Theft, Phishing, Online Impersonation",
        "offense_hi": "साइबर पहचान चोरी, फर्जी प्रोफाइल, ऑनलाइन ठगी",
        "bns_section": "BNS 318(4) read with IT Act Sec 66C & 66D",
        "bns_title": "Identity theft and cheating by personation using computer resource",
        "bns_act": "Information Technology Act 2000 & BNS 2023",
        "ipc_section": "IPC 420 / 419 read with IT Act Sec 66C & 66D",
        "ipc_title": "Cheating by personation using computer resource",
        "ipc_act": "Information Technology Act 2000 & IPC 1860",
        "nature": "Cognizable",
        "bailable": "Bailable (IT Act 66D) / Non-Bailable (BNS 318(4))",
        "compoundable": "Compoundable with court permission",
        "punishment": "Imprisonment up to 3 years and fine under IT Act; up to 7 years under BNS 318(4)",
        "triable_by": "Magistrate of the First Class",
        "bnss_procedure": "Mandatory preservation of electronic logs under Section 63 Bharatiya Sakshya Adhiniyam.",
        "victim_guidance": "Immediately dial 1930 within the 'Golden Hour' (first 2-3 hours) to freeze stolen funds in nodal accounts.",
        "accused_guidance": "Verify if your account was compromised or used as an unwitting mule account."
    },
    {
        "id": "cyber_stalking_voyeurism",
        "category": "Cyber Crime & Women Safety",
        "offense_en": "Cyber Stalking, Voyeurism & Obscene Content Publishing",
        "offense_hi": "साइबर स्टॉकिंग, बिना सहमति फोटो/वीडियो वायरल करना या अश्लीलता",
        "bns_section": "78 & 79 BNS read with IT Act 66E / 67",
        "bns_title": "Stalking, word/gesture outraging modesty, and violation of privacy",
        "bns_act": "Bharatiya Nyaya Sanhita, 2023 & IT Act, 2000",
        "ipc_section": "354D & 509 IPC read with IT Act 66E / 67",
        "ipc_title": "Stalking and word, gesture or act intended to insult modesty",
        "ipc_act": "Indian Penal Code, 1860 & IT Act, 2000",
        "nature": "Cognizable",
        "bailable": "Bailable (First offense) / Non-Bailable (Second conviction or under Sec 67A)",
        "compoundable": "Non-Compoundable",
        "punishment": "Up to 3 to 5 years imprisonment and fine",
        "triable_by": "Any Magistrate / Magistrate First Class",
        "bnss_procedure": "Special protection: Statement of victim recorded by woman magistrate under Sec 183 BNSS.",
        "victim_guidance": "Report immediately to cybercrime.gov.in under 'Women & Child' reporting section. URL/IP will be taken down.",
        "accused_guidance": "Engage counsel. Ensure no contact with complainant while proceedings or notices are pending."
    },
    {
        "id": "police_harassment_refusal",
        "category": "Police Powers & Citizen Rights",
        "offense_en": "Police Refusal to Register FIR / Illegal Detention",
        "offense_hi": "पुलिस द्वारा FIR दर्ज न करना या अवैध हिरासत में रखना",
        "bns_section": "BNSS Section 173(1), 173(3) & 175(3)",
        "bns_title": "Mandatory Registration of FIR & Application to Magistrate",
        "bns_act": "Bharatiya Nagarik Suraksha Sanhita, 2023",
        "ipc_section": "CrPC Section 154(1), 154(3) & 156(3)",
        "ipc_title": "Information in cognizable cases & complaint to Magistrate",
        "ipc_act": "Code of Criminal Procedure, 1973",
        "nature": "Statutory Mandate (Binding as per Supreme Court in Lalita Kumari)",
        "bailable": "N/A",
        "compoundable": "N/A",
        "punishment": "Disciplinary action & prosecution of police officer under BNS 198 (formerly IPC 166A)",
        "triable_by": "Judicial Magistrate",
        "bnss_procedure": "BNSS 173 introduces Zero FIR (mandatory registration anywhere) and e-FIR. If SHO refuses, send complaint to SP via registered post (Sec 173(4)), then file application before Magistrate under Sec 175(3) BNSS.",
        "victim_guidance": "1. Note down officer badge number. 2. Demand written acknowledgment. 3. If refused, file Zero FIR or approach SP/DCP directly. 4. Move application under Sec 175(3) BNSS.",
        "accused_guidance": "If detained without arrest memo or beyond 24 hours without Magistrate production, file Habeas Corpus petition under Art 226/32 or Sec 528 BNSS."
    },
    {
        "id": "domestic_violence",
        "category": "Family & Matrimonial",
        "offense_en": "Domestic Violence / Physical, Emotional, or Economic Abuse",
        "offense_hi": "घरेलू हिंसा (शारीरिक, मानसिक, भावनात्मक या आर्थिक प्रताड़ना)",
        "bns_section": "Section 12, 18, 19, 20 DV Act read with BNS 85/115",
        "bns_title": "Application to Magistrate under Protection of Women from Domestic Violence Act",
        "bns_act": "Protection of Women from Domestic Violence Act, 2005",
        "ipc_section": "Section 12 DV Act read with IPC 498A/323",
        "ipc_title": "Domestic Violence remedies",
        "ipc_act": "PWDVA 2005 & IPC 1860",
        "nature": "Quasi-Criminal / Civil with Criminal Enforcement",
        "bailable": "Bailable (Criminal arrest arises only upon breach of Protection Order under Sec 31)",
        "compoundable": "Compoundable",
        "punishment": "Protection orders, residence orders, monthly monetary maintenance, compensation",
        "triable_by": "Judicial Magistrate of the First Class",
        "bnss_procedure": "Expedited 60-day disposal mandate under Section 12(5) DV Act.",
        "victim_guidance": "Approach Protection Officer (PO), Service Provider, or directly file Section 12 petition before Magistrate for immediate Residence & Interim Maintenance.",
        "accused_guidance": "Reply to Section 12 notice within stipulated time. Produce bank records and evidence showing fair treatment and no deprivation."
    }
]
